<a href="https://colab.research.google.com/github/DavidCruz1013/etl-data-pipeline-2506162022/blob/main/etl_G_login.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://raw.githubusercontent.com/DavidCruz1013/etl-data-pipeline-2506162022/refs/heads/main/data/raw/G_login.csv

**Importamos la libreria de Panda**

In [1]:
import pandas as pd

**Cargar el CSV**

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DavidCruz1013/etl-data-pipeline-2506162022/refs/heads/main/data/raw/G_login.csv")

df.head()

  id_login id_usuario          fecha_login              ip
0   LG6000      US414  2024/08/22 05:00:00  192.168.18.198
1   LG6001      US418  2024-02-03 10:00:00   192.168.1.214
2   LG6002      US476  2024-01-11 21:00:00   192.168.20.28
3   LG6003      US449  2024-06-13 18:00:00  192.168.12.135
4   LG6004      US422  2024-08-26 00:00:00   192.168.11.22

**Explorar los datos**

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_login     236 non-null    object
 1   id_usuario   228 non-null    object
 2   fecha_login  229 non-null    object
 3   ip           233 non-null    object
dtypes: object(4)
memory usage: 7.5+ KB

id_login       0
id_usuario     8
fecha_login    7
ip             3
dtype: int64

**Crear copia para limpiar**

In [4]:
login = df.copy()

login.columns = login.columns.str.strip().str.lower()

for col in login.select_dtypes(include='object').columns:
    login[col] = login[col].astype(str).str.strip()

login = login.replace(r'^\s*$', pd.NA, regex=True)

**Limpieza de datos**

In [5]:
if 'fecha_login' in login.columns:
    login['fecha_login'] = pd.to_datetime(
        login['fecha_login'],
        errors='coerce'
    )

In [6]:
for col in login.select_dtypes(include='object').columns:
    login[col] = login[col].str.capitalize()

In [7]:
for col in login.columns:
    if 'id' in col or 'intento' in col:
        login[col] = pd.to_numeric(login[col], errors='coerce')

**Eliminar duplicados**

In [8]:
login = login.drop_duplicates()

**Separamos los validos con los datos rechazados**

In [9]:
validos = login.dropna().copy()

rechazados = login[login.isna().any(axis=1)].copy()

**Los posibles motivos de rechazo**

In [10]:
def motivo(row):
    columnas_invalidas = row[row.isna()].index.tolist()
    return ",".join(columnas_invalidas)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

**Conectar a PostgreSQL**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [11]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_cruz:QQKUpHpEiAA9Xpnfx2CpRPN4SRonP1Mc@dpg-d6qu6mc50q8c73bpejbg-a.oregon-postgres.render.com/etl_seguros_ej65"
engine = create_engine(database_url)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 69.8 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

**Insertar en la base de datos**

In [12]:
validos.to_sql(
    'g_login_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'g_login_rejects',
    engine,
    if_exists='append',
    index=False
)

218

**Verificamos los datos**

In [14]:
pd.read_sql(
"SELECT * FROM g_login_curated LIMIT 10",
engine
)

Empty DataFrame
Columns: [id_login, id_usuario, fecha_login, ip]
Index: []