<a href="https://colab.research.google.com/github/DavidCruz1013/etl-data-pipeline-2506162022/blob/main/etl_G_actividad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://raw.githubusercontent.com/DavidCruz1013/etl-data-pipeline-2506162022/refs/heads/main/data/raw/G_actividad.csv

**Importar librerias**

In [1]:
import pandas as pd

**Cargar el CSV**

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DavidCruz1013/etl-data-pipeline-2506162022/refs/heads/main/data/raw/G_actividad.csv")

df.head()

  id_actividad id_usuario             accion      fecha_actividad      modulo
0      ACT9000      US518  actualizar pedido  2024-05-20 07:00:00   seguridad
1      ACT9001      US512      cambio clave   2024-11-02 12:00:00    reportes
2      ACT9002      US450             logout  2024-08-29 19:00:00    usuarios
3      ACT9003      US467           consulta  2024-04-16 14:00:00   seguridad
4      ACT9004      US420           consulta  2024-08-08 05:00:00  inventario

**Explorar los datos**

In [3]:
df.shape
df.columns
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_actividad     246 non-null    object
 1   id_usuario       238 non-null    object
 2   accion           246 non-null    object
 3   fecha_actividad  240 non-null    object
 4   modulo           246 non-null    object
dtypes: object(5)
memory usage: 9.7+ KB

id_actividad       0
id_usuario         8
accion             0
fecha_actividad    6
modulo             0
dtype: int64

**Crear la limpieza de datos **

In [4]:
actividad = df.copy()

actividad.columns = actividad.columns.str.strip().str.lower()

for col in actividad.select_dtypes(include='object').columns:
    actividad[col] = actividad[col].astype(str).str.strip()

actividad = actividad.replace(r'^\s*$', pd.NA, regex=True)

**Convertimos las fecha si existen **

In [5]:
if 'fecha' in actividad.columns:
    actividad['fecha'] = pd.to_datetime(
        actividad['fecha'],
        errors='coerce'
    )

**Creamos las columnas numericas **

In [7]:
#por monto,valor,cantidad

for col in actividad.columns:
    if 'monto' in col or 'valor' in col or 'cantidad' in col:
        actividad[col] = actividad[col].astype(str).str.replace(',', '.', regex=False)
        actividad[col] = pd.to_numeric(actividad[col], errors='coerce')

**eliminamos datos duplicados **

In [8]:
actividad = actividad.drop_duplicates()

**Separar datos validos y rechazados**

In [9]:
validos = actividad.dropna().copy()

rechazados = actividad[actividad.isna().any(axis=1)].copy()

**Los motivos rechazados que pueden haber **

In [10]:
def motivo(row):
    columnas_invalidas = row[row.isna()].index.tolist()
    return ",".join(columnas_invalidas)

rechazados["motivo_rechazo"] = rechazados.apply(motivo, axis=1)

**Conectar a PostgreSQL**

In [11]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine

database_url = "postgresql://etl_cruz:QQKUpHpEiAA9Xpnfx2CpRPN4SRonP1Mc@dpg-d6qu6mc50q8c73bpejbg-a.oregon-postgres.render.com/etl_seguros_ej65"

engine = create_engine(database_url)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 54.7 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11

**Insertar en la base de datos**

In [12]:
validos.to_sql(
    'g_actividad_curated',
    engine,
    if_exists='append',
    index=False
)

rechazados.to_sql(
    'g_actividad_rejects',
    engine,
    if_exists='append',
    index=False
)

0

**Verificar datos**

In [14]:
pd.read_sql(
"SELECT * FROM g_actividad_curated LIMIT 20",
engine
)

   id_actividad id_usuario             accion      fecha_actividad      modulo
0       ACT9000      US518  actualizar pedido  2024-05-20 07:00:00   seguridad
1       ACT9001      US512       cambio clave  2024-11-02 12:00:00    reportes
2       ACT9002      US450             logout  2024-08-29 19:00:00    usuarios
3       ACT9003      US467           consulta  2024-04-16 14:00:00   seguridad
4       ACT9004      US420           consulta  2024-08-08 05:00:00  inventario
5       ACT9005      US477           consulta  2024-09-17 19:00:00   seguridad
6       ACT9006      US479       cambio clave  2024-07-07 11:00:00      ventas
7       ACT9007      US448       cambio clave  2024-09-09 06:00:00    reportes
8       ACT9008      US408             logout  2024-04-27 21:00:00   seguridad
9       ACT9009      US440  actualizar pedido  2024-07-27 11:00:00  inventario
10      ACT9010      US440       cambio clave  2024-10-13 10:00:00      ventas
11      ACT9011      US510             logout  2024-02-19 11:00:00  inventario
12      ACT9012      US465             logout  2024-11-13 17:00:00      ventas
13      ACT9013      US430              login  2024-07-19 03:00:00  inventario
14      ACT9014        nan              login  2024-03-11 19:00:00  inventario
15      ACT9015      US447       crear pedido           31/15/2024    usuarios
16      ACT9016      US462              login  2024-08-16 09:00:00   seguridad
17      ACT9017      US453      anular pedido  2024-02-20 22:00:00  inventario
18      ACT9018      US449       cambio clave  2024-05-03 13:00:00   seguridad
19      ACT9019      US500       cambio clave  2024-07-30 09:00:00    reportes